import type { Metadata } from "next";
import { Inconsolata } from 'next/font/google';
import "./globals.css";



const inconsolata = Inconsolata({
  subsets: ['latin'],         
  variable: '--font-inconsolata', 
})

export const metadata: Metadata = {
  title: "A Conference Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inconsolata.variable}
      >
        {children}
      </body>
    </html>
  );
}
